

export const VEHICLE_DETAILS_REQUEST = 'VEHICLE_DETAILS_REQUEST'
export const VEHICLE_DETAILS_SUCCESS = 'VEHICLE_DETAILS_SUCCESS'
export const VEHICLE_DETAILS_FAIL = 'VEHICLE_DETAILS_FAIL'
export const VEHICLE_DETAILS_RESET = 'VEHICLE_DETAILS_RESET'

export const VEHICLE_VERIFY_REQUEST = 'VEHICLE_VERIFY_REQUEST'
export const VEHICLE_VERIFY_SUCCESS = 'VEHICLE_VERIFY_SUCCESS'
export const VEHICLE_VERIFY_FAIL = 'VEHICLE_VERIFY_FAIL'
export const VEHICLE_VERIFY_RESET = 'VEHICLE_VERIFY_RESET'

export const VEHICLE_CREATE_REQUEST = 'VEHICLE_CREATE_REQUEST'
export const VEHICLE_CREATE_SUCCESS = 'VEHICLE_CREATE_SUCCESS'
export const VEHICLE_CREATE_FAIL = 'VEHICLE_CREATE_FAIL'
export const VEHICLE_CREATE_RESET = 'VEHICLE_CREATE_RESET'

export const VEHICLE_UPDATE_REQUEST = 'VEHICLE_UPDATE_REQUEST'
export const VEHICLE_UPDATE_SUCCESS = 'VEHICLE_UPDATE_SUCCESS'
export const VEHICLE_UPDATE_FAIL = 'VEHICLE_UPDATE_FAIL'
export const VEHICLE_UPDATE_RESET = 'VEHICLE_UPDATE_RESET'



